#!/bin/bash

set -o errexit
set -o nounset

setup_local_bin(){
	DIR=/home/ubuntu/.local
	sudo mkdir -p ${DIR}
	sudo chown -R ubuntu ${DIR}
	echo 'PATH=${PATH}:${HOME}/.local/bin' >> /home/ubuntu/.bashrc
}

setup_repositories(){
	sudo apt-get update --yes
	sudo apt-get upgrade --yes
	sudo apt-get install --yes parallel htop jq screen
}

setup_ebs_storage(){
	sudo mkdir -p /mnt
	echo '/dev/xvdf       /mnt    ext4    defaults,nofail 0 2' | sudo tee --append /etc/fstab
}

setup_repositories
setup_local_bin
setup_ebs_storage

# Destroy possibly sensitive keys
sudo shred --remove /etc/ssh/*_key /etc/ssh/*_key.pub

# Remove code preventing non-interactive bashrc evaluation
sed -i 5,10d .bashrc
