#!/bin/bash

set -o errexit
set -o nounset

chmod 700 /home/ubuntu/.local/bin/start_benchmarks.sh

sudo shred --remove /etc/ssh/*_key /etc/ssh/*_key.pub

sudo apt-get update --yes
sudo apt-get upgrade --yes
sudo apt-get install --yes parallel htop jq screen
